import type { Exhibitor } from "../viewer/types";

import logoAcme from "./logos/acme-corp.svg";
import logoTechflow from "./logos/techflow.svg";
import logoGreenleaf from "./logos/greenleaf.svg";
import logoNexus from "./logos/nexus.svg";
import logoHorizon from "./logos/horizon.svg";
import logoCloudbridge from "./logos/cloudbridge.svg";
import logoSummit from "./logos/summit.svg";
import logoVanguard from "./logos/vanguard.svg";
import logoPulse from "./logos/pulse.svg";
import logoBrightpath from "./logos/brightpath.svg";

// ── Main Exhibition Hall (alpha codes, 10 exhibitors) ─────────────────────────
export const sampleExhibitors: Exhibitor[] = [
  { id: "exh-001", name: "Acme Corp",            boothCode: "A101", logo: logoAcme },
  { id: "exh-002", name: "TechFlow Inc",          boothCode: "A102", logo: logoTechflow },
  { id: "exh-003", name: "GreenLeaf Solutions",   boothCode: "A103", logo: logoGreenleaf },
  { id: "exh-004", name: "Nexus Digital",         boothCode: "B101", logo: logoNexus },
  { id: "exh-005", name: "Horizon Events",        boothCode: "C101", logo: logoHorizon },
  { id: "exh-006", name: "CloudBridge AI",        boothCode: "C102", logo: logoCloudbridge },
  { id: "exh-007", name: "Summit Audio",          boothCode: "C104", logo: logoSummit },
  { id: "exh-008", name: "Vanguard Media",        boothCode: "D101", logo: logoVanguard },
  { id: "exh-009", name: "Pulse Analytics",       boothCode: "D103", logo: logoPulse },
  { id: "exh-010", name: "BrightPath Learning",   boothCode: "D105", logo: logoBrightpath },
];

// ── Conference & Expo Hall 2026 (numeric codes, 100 exhibitors) ───────────────
// IDs are real PheedLoop-format slugs. Booth codes match conferenceExpoBooths
// in sample-booths.ts. Unassigned booths (2, 3, 4, 6–10, etc.) have no exhibitor.
export const conferenceExpoExhibitors: Exhibitor[] = [
  { id: "EXHH5CSK30LVYLKFX", name: "Harbor Capital",              boothCode: "1"   },
  { id: "EXHS1K9YE9O2M71HS", name: "Lantern Advisory",            boothCode: "5"   },
  { id: "EXHCMKTLZKJ49YD82", name: "Vortex Cybersecurity",        boothCode: "11"  },
  { id: "EXHP2U4DTBH55RBC7", name: "Tangent Engineering",         boothCode: "12"  },
  { id: "EXH4N89QKNS832EJX", name: "Vertex Industries",           boothCode: "13"  },
  { id: "EXHY36DDFGS3JONOU", name: "Relay Communications",        boothCode: "15"  },
  { id: "EXH3C9XQYM52XG8P6", name: "Lumina Technologies",         boothCode: "16"  },
  { id: "EXHYN9382KKZMPJRH", name: "Sapphire Diagnostics",        boothCode: "18"  },
  { id: "EXHGYSPENGWYX9TRF", name: "Quantum Leap AI",             boothCode: "20"  },
  { id: "EXHTJ1GM25LEN606N", name: "Cobalt Manufacturing",        boothCode: "21"  },
  { id: "EXH1AT7O75RH8LX6D", name: "Umbra Defense",               boothCode: "24"  },
  { id: "EXHY8N1UTOXIE0RNU", name: "Solstice Media",              boothCode: "25"  },
  { id: "EXH9RR7S20CV3TLCX", name: "Eclipse Energy",              boothCode: "26"  },
  { id: "EXH9YO18PAJSSUUQO", name: "Keyframe Media",              boothCode: "27"  },
  { id: "EXHJA2M0W10LBT3G2", name: "Paragon Software",            boothCode: "30"  },
  { id: "EXH8O1BJ9RM7PYXDW", name: "Watershed Environmental",     boothCode: "31"  },
  { id: "EXH6UB7L8V1ZOCFI4", name: "Uplift Social",               boothCode: "32"  },
  { id: "EXHW5WFCPKJCSLQC3", name: "Meridian Healthcare",         boothCode: "33"  },
  { id: "EXH1RSRLA8S8HMBR5", name: "Jasper Therapeutics",         boothCode: "35"  },
  { id: "EXHVWVM4W3ZKWDEEK", name: "Pipeline Energy",             boothCode: "36"  },
  { id: "EXH0WFOY4DD1VN8LF", name: "Deepwater Energy",            boothCode: "37"  },
  { id: "EXHMUFM8ZOV7LN23Y", name: "NovaTech Systems",            boothCode: "38"  },
  { id: "EXHFHV1XG1R11Q7UW", name: "Apex Solutions",              boothCode: "39"  },
  { id: "EXHGFU8IOGXPBWHVN", name: "Northgate Medical",           boothCode: "40"  },
  { id: "EXH3OEUVTYT8QZPKY", name: "Highpoint Analytics",         boothCode: "42"  },
  { id: "EXH6NOUHFJ7UPFLN4", name: "Navigate Financial",          boothCode: "43"  },
  { id: "EXHC54WSQT26Q3XLR", name: "Stellar Communications",      boothCode: "44"  },
  { id: "EXH9N56NYXTXMGTT0", name: "Echo Analytics",              boothCode: "45"  },
  { id: "EXH3P15AHDBVZB0OI", name: "Glacier Pharma",              boothCode: "46"  },
  { id: "EXHH6T1NTMJSRD9Q4", name: "Momentum Healthcare",         boothCode: "48"  },
  { id: "EXH795E5IZ31YRUJO", name: "Wavefront Imaging",           boothCode: "52"  },
  { id: "EXHQXMCTHPHJ3MUUR", name: "Yellowstone Environmental",   boothCode: "55"  },
  { id: "EXH2ZCFZW0LDALMJE", name: "Crossroads Ventures",         boothCode: "56"  },
  { id: "EXHBMC97C7BO119XP", name: "Drift Technologies",          boothCode: "57"  },
  { id: "EXHIUI9KKHZLM72JE", name: "Radius Cybersecurity",        boothCode: "58"  },
  { id: "EXHNWYWRRATATJ9A3", name: "Quorum Data",                  boothCode: "59"  },
  { id: "EXHSBELRQVSLWF90K", name: "Mosaic Creative",             boothCode: "60"  },
  { id: "EXH0UR5L8A78E9RIV", name: "Lattice Materials",           boothCode: "63"  },
  { id: "EXH1VSMADO8E7FLQH", name: "Landmark Real Estate",        boothCode: "66"  },
  { id: "EXHCCPRHVLZ049ENU", name: "Halcyon Systems",             boothCode: "67"  },
  { id: "EXHXQT4P501NOUHTC", name: "Keystone Engineering",        boothCode: "68"  },
  { id: "EXH3N3BZT9D31K9QM", name: "Threadneedle Finance",        boothCode: "69"  },
  { id: "EXHMABSI9NB74X2EK", name: "Atlas Consulting",            boothCode: "72"  },
  { id: "EXHRXYJ38XRG2GZR7", name: "Onyx Defense",                boothCode: "74"  },
  { id: "EXHIAAKYTT3IMJ70E", name: "Forge Manufacturing",         boothCode: "75"  },
  { id: "EXHLQJIDKNWI5FLUL", name: "Icefall Analytics",           boothCode: "77"  },
  { id: "EXHLQBMAE38SRYO4R", name: "Riviera Hospitality",         boothCode: "79"  },
  { id: "EXH5TD44K1J6FP8HQ", name: "Prism Marketing",            boothCode: "80"  },
  { id: "EXH0DL5E11E9FTAXP", name: "Clarity Analytics",           boothCode: "81"  },
  { id: "EXH3P91I3VMZWFFHH", name: "Upstream Biotech",            boothCode: "82"  },
  { id: "EXHDS3QSQCQ30O30U", name: "Citadel Security",            boothCode: "83"  },
  { id: "EXHGQTOAMDVLNKND6", name: "Dynamo Systems",              boothCode: "84"  },
  { id: "EXHRRPZLK3E4XYF9I", name: "Milestone Capital",           boothCode: "85"  },
  { id: "EXHXUX1OXRWK8R2YK", name: "Griffin Automation",          boothCode: "86"  },
  { id: "EXH7YT2M6TWD1XMXB", name: "Jetstream Aviation",          boothCode: "87"  },
  { id: "EXH32ORWIXZ2C9ROS", name: "Interchange Logistics",       boothCode: "89"  },
  { id: "EXHQW5DSK7N8LA100", name: "Xcelerate Performance",       boothCode: "90"  },
  { id: "EXHKTSG7FXZV4U3BB", name: "Emerald Sustainability",      boothCode: "91"  },
  { id: "EXHZAREIYAZ39PECN", name: "Brightside Healthcare",        boothCode: "92"  },
  { id: "EXHCB1KJTGQ01TEE1", name: "Scaffold Construction",       boothCode: "94"  },
  { id: "EXHT7ZEWVIYTWBOZD", name: "Tempest Aviation",            boothCode: "95"  },
  { id: "EXHFCD6MZSGIPPSFN", name: "Quantum Analytics",           boothCode: "96"  },
  { id: "EXHHKC856WPR97Y2L", name: "Ignite Marketing",            boothCode: "97"  },
  { id: "EXH3FPOYIPK0QTL3Q", name: "Summit Financial",            boothCode: "100" },
  { id: "EXH9EL8HL88KZRUIN", name: "Groundwork Infrastructure",   boothCode: "103" },
  { id: "EXHO6L1F90S9BP4M1", name: "Vector Genomics",             boothCode: "104" },
  { id: "EXH4LMCT64Z7W2SEH", name: "Arcadia Healthcare",          boothCode: "105" },
  { id: "EXHR821UZVGWW4FYB", name: "Olympus Capital",             boothCode: "106" },
  { id: "EXHYCELOS6ZLE6KWH", name: "Zephyr Clean Energy",         boothCode: "107" },
  { id: "EXH69UGNEKRCPPRCJ", name: "Element Life Sciences",       boothCode: "109" },
  { id: "EXHIWVHDK8LW2LM34", name: "Foundry Partners",            boothCode: "110" },
  { id: "EXHKOMV2XCDYK0X65", name: "Pinnacle Engineering",        boothCode: "112" },
  { id: "EXHKBP2QD6VASIFPW", name: "Ironclad Security",           boothCode: "113" },
  { id: "EXHN2Y8FV2BC2NNUV", name: "Vanguard Aerospace",          boothCode: "114" },
  { id: "EXHZH13CD5GLQJ5SX", name: "Origin Technology",           boothCode: "115" },
  { id: "EXHEF0VOTQTXHI15C", name: "Acorn Biomedical",            boothCode: "116" },
  { id: "EXHOFN1R4KZ36U8UE", name: "Junction Software",           boothCode: "117" },
  { id: "EXHQZCUCTSUFLSEHU", name: "Beacon Logistics",            boothCode: "118" },
  { id: "EXHEFQJG02U1G463S", name: "Xenith Medical",              boothCode: "119" },
  { id: "EXH9IY4X41DNTCAGR", name: "Sienna Agriculture",          boothCode: "121" },
  { id: "EXHLXSLG6MM1ZXYVG", name: "Quasar Networks",             boothCode: "122" },
  { id: "EXHOLMLGSES6M033I", name: "TechVentures Inc.",           boothCode: "123" },
  { id: "EXHC4D145BM1ENF31", name: "Horizon Medical",             boothCode: "124" },
  { id: "EXH75AUD9K9TR74QG", name: "Wildfire Communications",     boothCode: "125" },
  { id: "EXHQZW3C1QKBHB7S9", name: "Redwood Pharmaceuticals",     boothCode: "126" },
  { id: "EXHLVPYMB5M9J98CW", name: "Polaris Logistics",           boothCode: "129" },
  { id: "EXHE2ATN2TWDL9ZS1", name: "Titan Construction",          boothCode: "130" },
  { id: "EXHIHX74D0GJYV5G1", name: "Kinetic Robotics",            boothCode: "132" },
  { id: "EXHMYBD2QE4PA8HYE", name: "Zeal Marketing",              boothCode: "135" },
  { id: "EXH3ZEZQACJ4T0SEK", name: "Nexus Biotech",               boothCode: "137" },
  { id: "EXHXF7JXJN6FOKZIX", name: "Archway Consulting",          boothCode: "139" },
  { id: "EXHDYGFLIJI18K0AX", name: "Yield Analytics",             boothCode: "140" },
  { id: "EXHUT076G5G79OR78", name: "Valor Financial",             boothCode: "141" },
  { id: "EXHIOXD9CSS9TOQW9", name: "BlueSky Robotics",            boothCode: "143" },
  { id: "EXHM3TZK3NY9V20YA", name: "Nautilus Marine",             boothCode: "144" },
  { id: "EXH30YSXPNNGH8RIE", name: "Cascade Digital",             boothCode: "145" },
  { id: "EXHJJQ9K6RE4Q6QDY", name: "Zenith Instruments",          boothCode: "147" },
  { id: "EXHBEFFLZM764JWTE", name: "Orbit Data",                  boothCode: "148" },
  { id: "EXH8DALFYO1750CEH", name: "Prestige Genomics",           boothCode: "149" },
  { id: "EXHTXCB48Y1O4IZAS", name: "Pathfinder Consulting",       boothCode: "150" },
];
